version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  eos-actions-fetcher:
    build: .
    container_name: eos-actions-fetcher
    depends_on:
      - mongo

volumes:
  mongo-data: